---
## Imports differetes tasks to ansible
  - name: Apply import firewall
    import_tasks: firewall-dp.yml

# Execute the task only if the load_config is enable on default.
  - name: Load a configurion 
    import_tasks: firewall-load.yml 
    when: load_config == "enabled"